all:
  hosts:
    localhost:
  children:
    web:
      hosts:
        localhost:
    database:
      hosts:
        localhost:
    cache:
      hosts:
        localhost:
    message:
      hosts:
        localhost:
    monitor:
      hosts:
        localhost:
