# bootstrapping
- hosts: all
  become: true
  tasks:
    - name: install common packages & repositories
      become: true
      yum:
        name:
          - "@Development Tools"
          - epel-release
          - https://centos7.iuscommunity.org/ius-release.rpm
      tags:
        - insatall
        - configuration

# configuration
- hosts: cache
  roles:
    - role: redis
- hosts: database
  roles:
    - role: debug
      foo: database playbook
- hosts: message
  roles:
    - role: debug
      foo: message playbook

# orchestration
- hosts: web
  roles:
    - role: debug
      foo: web playbook

#
- hosts: monitor
  roles:
    - role: debug
      foo: monitor playbook
