#
- hosts: all
  become: true
  roles:
    - role: stub
      msg: all
  tags:
    - bootstrapping

#
- hosts: cache
  roles:
    - role: stub
      msg: cache

- hosts: database
  roles:
    - role: stub
      msg: database

- hosts: message
  roles:
    - role: stub
      msg: message

#
- hosts: web
  roles:
    - role: stub
      msg: web

#
- hosts: monitor
  roles:
    - role: stub
      msg: monitor
